Repository jferragut/alkemy, pull requests merged in 2019-10, with the labels that each got.

#62 Update README.md
  README.md
Labels: enhancement

#69 fix height of hover to fill card
  src/assets/css/style.css
  src/assets/css/style.css.map
  src/assets/css/style.scss
Labels: bug

#70 BUG: card-deck not centered
  src/assets/css/style.css
  src/assets/css/style.css.map
  src/assets/css/style.scss
  src/components/BlogWidget.jsx
Labels: Development, bug

#67 Blog card CSS fix
  src/assets/css/animate.css
  src/assets/css/style.css
  src/assets/css/style.css.map
  src/assets/css/style.scss
Labels: Development, bug

#77 Added import for fontawesome SSR fix
  gatsby-browser.js
  src/components/layout.js
Labels: Development, bug

#79 Blog card truncate
  src/components/BlogWidget.jsx
  src/pages/alkemy-blog.js
  src/pages/index.js
  src/utils/utils.js
Labels: Development, bug
